### ISSUE TITLE
gutentags does not respect ctags option [--append=yes]

### ISSUE THREAD

**Issue by josefson** [ludovicchabant/vim-gutentags#104]
I need to index external 3rd party libs tags to my current project, and since gutentags doesn't allow me to provide my own ctags command line options, i am making use of the `.ctags` file which i'm filling it with my options.
However `.ctags` doesn't allow for us to pass directories as it's options. So i'm doing it through a shell function and calling it eventually to append my project tags file.
The thing is, whenever i call `ctags` from cmdline for both, my 3rd party libs and my project directory, the `tags` file gets appended and we can either see it through `--totals=yes` or through `wc tags`.
Here are the symptoms:

- If i created the `tags` file with the external libs while vim was open, gutentags would only overwrite it upon new file creation: `:e newfile.ext` or loading a bew buffer created outside vim.
- Every time i restart vim it would also overwrite it.

From what i have tested the damage is being done by `let g:gutentags_generate_on_new = 1`, which from docs says:

> If set to 1, Gutentags will start generating the tag file when a new project is open. A new project is considered open **_when a buffer is created for a file whose corresponding tag file has not been "seen" yet_** in the current Vim session -- which pretty much means when you open the first file in a given source control repository.

So, my conjecture is that gutentags is not recognizing the `tags` file as an actual `tags` file and therefore it is creating/overwriting it as if the project was brand new, and maybe when the project is brand new, one would not care about the `--append=yes` option.
When this is set to 0, it doesn't overwrite my tags file. And I don't think this is the expected behavior.

**Comment by ludovicchabant** [comment]
Hi,

So `gutentags_generate_on_new` regenerates the whole tags file for the whole project on purpose. This is because if this is the first time you open a file in a given project in a given Vim session, there's a good chance a whole bunch of things could have happened -- it could be the first time you re-open Vim on a monday after syncing/pulling/merging or whatever. So to be safe we just re-index the whole project and go incrementally from there. You could disable that setting of course.

When you say you can't pass directories in `.ctags` do you mean you want to index more stuff than what is in your repo? Like you would want Gutentags to additionally index some 3rd party libraries?

Logically I would expect one tags file to correspond to one project. Many people may want to use them differently but in the interest of remaining sane, and keeping Gutentags from exploding with different modes, that's what I think I will stick to. So your project, and each 3rd party library, should each have their own tags file in my opinion. Now thankfully, Vim supports having multiple tags files active for any given buffer... so what I'd recommend is to let Gutentags do what it wants, but add some ad-hoc Vim callbacks that add the 3rd party libraries' tags files to each buffer that you open in your project. Does that make sense?

**Comment by ludovicchabant** [comment]
Closing old issues.
