### ISSUE TITLE
Is there a way to default the `project_root` to the present working directory?

### ISSUE THREAD

**Issue by austincrft** [ludovicchabant/vim-gutentags#105]
Sometimes a repo contains multiple "projects". I understand it's not a best-practice, but I see it pretty frequently. It'd be nice to be able to have gutentags always use the `:pwd` as the `project_root`.

I tried it with these settings, but it isn't working the way I'm anticipating.

``` vim
function! GetPwd(path)
    return execute(':pwd')
endfunction

let g:gutentags_project_root_finder='GetPwd'
let g:gutentags_add_default_project_roots=0
```

Am I doing something wrong?

**Comment by austincrft** [comment]
I suppose this is kind of related to #86, because the desire is to run the command from `:pwd` instead of the current file's path.

**Comment by josefson** [comment]
Since gutentags start the introspection of where the root project will be from the filepath up to the projectroot, wouldn't add something to `let g:gutentags_project_root = []` that would characterize the subproject as another root project work?
Although one would have to point the new tags file to vim, if you are in the masterproject as your cwd. Also, i don't know how adding a new `gutentags_project_root = []` would behave, i am assuming it will stop going up dirs as it matches something in the list.

**Comment by ludovicchabant** [comment]
If a repo contains multiple projects, you could figure out additional root markers for those projects -- or add your own if there's nothing of the sort. For instance, you could add a `.myproject` file at the root of each of those projects, and add that file name to Gutentags' root markers?

**Comment by austincrft** [comment]
I'm sure I can hack together a solution, but I was suggesting a more complete solution. Something like [ctrlp.vim's `g:ctrlp_working_path_mode` option](https://github.com/ctrlpvim/ctrlp.vim#basic-options).

With this setting, you can specifiy that all searches take place from the current working directory. In gutentags, I'd like to be able to specify that all tagging takes place from the current working directory.

I will look into implementing this if I can't find a decent solution.

**Comment by ludovicchabant** [comment]
Actually looking back at your original post, I think your problem is simply that `execute(':pwd')` won't return anything as far as I know? You might have better luck with `return getcwd()`.

Of course you're then responsible for managing your CWD, otherwise Gutentags might run `ctags` on a whole bunch of wrong directories.

**Comment by austincrft** [comment]
That doesn't seem to work either. As it is now, it's just easier to create a mapping like this

``` vim
nnoremap <leader>pT :Start! ctags -R<CR>
```

And run it manually as needed.

**Comment by ludovicchabant** [comment]
Well, your code with the fix to use `return getcwd()` works fine for me. Ping me if you want to figure it out.

**Comment by smemsh** [comment]
this seems to help when moving around vim's cwd (ie with ":cd")
```
autocmd DirChanged global call gutentags#rescan()
```
or binding it to some macro sequence and remembering to do it
