### ISSUE TITLE
Automatic exclusion of directories in .gitignore

### ISSUE THREAD

**Issue by LukaK** [ludovicchabant/vim-gutentags#108]
Hi,
first thank you for the plugin, i enjoy using it.

In the future, do you plan to add .gitignore parsing to automatically exclude  directories from being processed by ctags?

**Comment by ludovicchabant** [comment]
Hi!

I've thought about it, but I decided against it.

First, not everybody uses Git (I personally use Mercurial primarily at home, and my workplace is using Perforce). So we would have to implement potentially multiple parsers. Second, everything that's not in source control should not necessarily be excluded from tags indexing, and vice versa. For instance, some of the codebases I work with make extensive use of code generation, so there's a lot of code files that are excluded from source control but that I definitely want in my tags files.

So what I'm saying is: I would be OK if someone was to submit a PR that offers the feature as an option, but since I would personally not use it, I won't implement it.
