### ISSUE TITLE
Wishlist: option to have gutentags update existing tags files but not create new ones

### ISSUE THREAD

**Issue by mgedmin** [ludovicchabant/vim-gutentags#113]
I would like gutentags to update existing tags files on save in projects where I already use ctags, but I would like to avoid the tags file clutter in all other git repositories such as my ~/.vim/.  I've asked vim-gutentags to

```
  let g:gutentags_generate_on_new = 0
  let g:gutentags_generate_on_missing = 0
```

but still, whenever I edit a ~/.vim/plugins/foo.vim, I discover a new ~/.vim/tags file.

Could we please have a weaker version of `g:gutentags_generate_on_write` that would only do the generation when it finds an existing `tags` file?

**Comment by ludovicchabant** [comment]
You could either:

1) set `g:gutentags_init_user_func` to a user-defined function that returns 1 only if there's a `tags` file somewhere in the parent hierarchy

OR 

2) set `g:gutentags_project_root` to `['tags']` and `g:gutentags_add_default_project_roots` to 0 so that the *only* root marker Gutentags would be looking for is `tags`.

Does that make sense?

**Comment by mgedmin** [comment]
Yes, thank you!

**Comment by ludovicchabant** [comment]
Great :)
