### ISSUE TITLE
latest update errors

### ISSUE THREAD

**Issue by davidosomething** [ludovicchabant/vim-gutentags#114]
```
"drawer.js" 153L, 3514C
Error detected while processing function gutentags#setup_gutentags[88]..<SNR>184_update_tags[34]..gutentags#ctags#generate:
line   50:
E117: Unknown function: matchstrpos
E15: Invalid expression: matchstrpos(l:file_list_cmd, '///')
Error detected while processing function gutentags#setup_gutentags:
line   88:
E171: Missing :endif
```

on neovim 1.7

**Comment by ludovicchabant** [comment]
Weird, there's no indication in the Vim docs that the `matchstrpos` function is new or has changed in recent versions of Vim... so I assume that's something that Neovim just doesn't support for some ungodly reason.

If you have any knowledge of Neovim and can offer and equivalent piece of code that works on both, please file a PR. Otherwise I'll have to install Neovim and give it a try when I get some time.

**Comment by bitboxer** [comment]
I also have a weird thing in my vim now: it only offers me the `GutentagsUnlock` command. Everything else is gone.

**Comment by zandrmartin** [comment]
According to the folks in #neovim, `matchstrpos()` will be implemented in Neovim 0.2.0 - this was a function added to Vim in version 8.0. I'm also experiencing the same problems as @bitboxer.

**Comment by rafi** [comment]
@bitboxer try #116

**Comment by zandrmartin** [comment]
@rafi #116 fixes the problems for me. I guess the `matchstrpos()` problem is not related to the missing commands problem.

**Comment by bitboxer** [comment]
Yes, fixes the problem for me, too. Thanks!

**Comment by JohanBjoerklund** [comment]
#116 Works like a charm

**Comment by davidosomething** [comment]
now using     `Plug 'rafi/vim-gutentags', { 'branch': 'fix/globpath' }` from #116 but #114 not fixed for me

**Comment by rafi** [comment]
@davidosomething two suggestions:
* Try executing in Neovim `:echo matchstrpos('abcdEfg', 'cd')`
* Check if you're loading the plugin correctly with your plugin-manager and maybe try to load it lazily..

**Comment by davidosomething** [comment]
@rafi we covered that -- on neovim 1.7 (which is the current official release), `matchstrpos` is not available

**Comment by frangio** [comment]
@davidosomething The segfault you refer to was not in HEAD, but in a pull request. It's fixed now, anyway.

**Comment by psjay** [comment]
Same problem when I turned on the gutentags_file_list_command settings on NeoVim 1.7.

**Comment by smkent** [comment]
`matchstrpos` appears to be Vim patch 7.4.1685: http://ftp.vim.org/vim/patches/7.4/7.4.1685

I work with several machines that are Ubuntu 14.04 LTS (or derivatives). Vim on those operating systems predates this patch and I'm now running into this problem:

![114](https://cloud.githubusercontent.com/assets/2831985/25216081/b18adcd8-2555-11e7-8032-d23cf8e0be16.png)

The net effect here is Gutentags doesn't work on these older (but still OS vendor-supported) systems.

Ideally, `matchstrpos` should be removed and replaced with something that is more backwards-compatible. Otherwise, feature(s) that require `matchstrpos` should be disabled if patch 7.4.1685 is not available:

```vim
if has('patch-7.4.1685')
    " etc.
endif
```

The specific error I'm seeing appears to be in `autoload/gutentags/ctags.vim`, where Gutentags is deciding if the file list command should use the `-A` (absolute paths) option, introduced in 1cb511de7576c0271f3505c39412a83a3b24fc88. `git grep` doesn't show any other instances of `matchstrpos` in Gutentags.

**Comment by smkent** [comment]
A simpler way to check if `matchstrpos` is available is:

```vim
exists("*matchstrpos")
```

**Comment by smkent** [comment]
I believe the particular instance of `matchstrpos()` introduced by 1cb511de7576c0271f3505c39412a83a3b24fc88 can be replaced with a combination use of `match()` and `split()`, which are both available in older versions of Vim.

See my pull request for more info: https://github.com/ludovicchabant/vim-gutentags/pull/132

**Comment by davidosomething** [comment]
^ works for me

**Comment by ludovicchabant** [comment]
@smkent's PR has been now merged! I think I can close this now as a result...
