### ISSUE TITLE
Generate tags file asynchronously

### ISSUE THREAD

**Issue by tbodt** [ludovicchabant/vim-gutentags#121]
I have `autocmd TextChanged,InsertLeave nested silent! update`, so whenever I change anything the editor freezes for a few hundred milliseconds while it updates the tags file. This is getting pretty annoying...

**Comment by justinmk** [comment]
This raises the question: @ludovicchabant do you plan to use job control in vim8, soon?

**Comment by tbodt** [comment]
Or Neovim job control? I'm using Neovim...

**Comment by justinmk** [comment]
@ludovicchabant Doesn't use neovim, but if he does the vim8 job thing it won't take long to adapt it for neovim.

**Comment by ludovicchabant** [comment]
Hi there,

The tags file is already being updated asynchronously by spawning a script that takes care of the heavy lifting. So the only thing you would save by using the job API from Vim8/Neovim would be the ~50 lines of Vimscript that do the preparation for running that script.

Therefore I'm not sure exactly if using background jobs would do a lot of difference -- I don't know if they have overhead or whatever. I do have it on my TODO list to try it out, if only to remove the need for creating a `.lock` file, but that's low priority. And actually, I imagine most of the freezing you notice must be Gutentags checking for the existing of that `.lock` file on disk.

**Comment by justinmk** [comment]
>  the only thing you would save by using the job API from Vim8/Neovim would be the ~50 lines of Vimscript that do the preparation for running that script.

Using job-control would avoid accidentally leaving the temp/marker files (or creating them in the first place).

> I don't know if they have overhead or whatever.

Overhead...?

**Comment by tbodt** [comment]
It seems like there's a non-trivial amount of overhead (~400ms) to executing an external command in vim without job control. If you do `:!echo hi` there's a very noticeable pause before you can use the editor again. @justinmk probably knows more than me about why this is the case.

**Comment by justinmk** [comment]
Depends on how it's invoked, but at least one benefit of `job_start()` is that if you pass the args as a List then it is run "directly", i.e. without a shell. Whereas `:!` and `system()` always use the shell (except in nvim if `system()` args are passed as a List--analogous to jobstart/job_start).

400ms seems high though.

**Comment by tbodt** [comment]
I made a 4-second video to illustrate what's going on: https://www.youtube.com/watch?v=NSAjNQpCX_U

I typed `:call system('echo hi')` and immediately hit i and started pressing keys. By the time the command has finished, I've inputted 6 characters. I would expect it to not take a noticeable amount of time at all. This is with `nvim -u NONE`, the same thing happens in `vim -u NONE`.

**Comment by justinmk** [comment]
@tbodt Could be your bashrc/profile/etc. Try a different shell.

See also https://github.com/vim/vim/issues/1089 and https://groups.google.com/d/msg/vim_dev/PmNEtGLv6J0/xj80VAteAgAJ .

Even so, it's still an argument in favor of job control IMO.

**Comment by tbodt** [comment]
Hey, that makes sense. My shell is fish.

~Theodore

**Comment by ludovicchabant** [comment]
I'm using Fish also, but I can absolutely not "miss out" keys like you did in the video... even though I'm on an 8-years old Macbook Pro... My Fish config file is pretty minimal though.

Either way yes, using jobs will certainly be a nice improvement. If anybody has time to do it, please go for it :)  Otherwise I'll do it at some point but I have no ETA as to when that would be.

**Comment by tbodt** [comment]
I've got a lot of crap clogging up my fish configuration, it turns out. I spend a bit of time the other day reducing the startup time from 500 ms to 50 ms. It's really helped a lot.

**Comment by ludovicchabant** [comment]
Okay people, it's a long week-end so I figured I'd hack around with the Vim8 jobs! So the latest code updates include:

- Using `job_start`/`jobstart` (Vim8 _vs_ Neovim... I wish Neovim would just deprecate its API at this point) for launching the tags generation. No changes here from before since it was already launching a background process before, albeit using the shell.
- Gets rid of all the lock file business... like I said, this is a nice thing. The tag generation script still creates/deletes the lock file though, because, I don't know, why not? But the Vim plugin doesn't care anymore at this point.
- As another nice side-effect, if you added `gutentags#statusline` to your statusline, you can now use the `GutentagsUpdating` and `GutentagsUpdated` user events to force-refresh it and get proper real-time information about when tags are generating or not. See the changes to the documentation for an example with `lightline`.
- The requirements for Gutentags have been bumped to Vim 8 or Neovim, as I didn't want to support 2 code paths (with/without jobs). If you still need to use Vim 7, you can checkout the `vim7` branch, which I'll support for a while.

I have tested the new code with a good combination of use cases, but bugs will probably creep up here and there so as always feel free to open new issues.

**Comment by justinmk** [comment]
> The tag generation script still creates/deletes the lock file though, because, I don't know, why not?

Why not: because it's annoying to see it appear in `git status`.

> I wish Neovim would just deprecate its API at this point

A lot of thought was put into the Neovim jobs API to make it powerful yet easy to use.  If you don't want to think about the differences, you can inline https://github.com/prabirshrestha/async.vim which is a thin abstraction around Vim8/Nvim jobs APIs.

**Comment by ludovicchabant** [comment]
Ah thanks for the pointer to `async.vim`, this might indeed come in handy, although I already wrote my own ad-hoc thin wrapper so we'll see if it can hold up for the limited use we have of it.

About the lock file, you probably already have `tags` in your global `.gitignore`, so you could also add `tags.lock`, but I see you point and I'll remove the lock file in the future.

**Comment by hrai** [comment]
> About the lock file, you probably already have `tags` in your global `.gitignore`, so you could also add `tags.lock`, but I see your point and I'll remove the lock file in the future.

This is what I'm currently doing in my global gitignore file.
