### ISSUE TITLE
How to use .gutctags?

### ISSUE THREAD

**Issue by rawaludin** [ludovicchabant/vim-gutentags#126]
I've read the doc, but still can't understand it. I want to limit my php generation tag to use this options:

```
ctags -R --languages=php --php-kinds=cfit
```

I've created `.gutctags` in current project file with following content:
```
-R
--languages=php
--php-kinds=cfit
```

But it looks like gutentags still use his rule when generating tags.

Any clue?

**Comment by ludovicchabant** [comment]
This looks correct, assuming the `.gutctags` file is in the right place (at the projet's root).

Can you execute `:call gutentags#toggletrace()` and then `:GutentagsUpdate!` ? You should see some messages in Vim telling you how the update script was invoked. If everything went well, it should pass the path to your `.gutctags` file with the `-o` option... if it's not there, then most likely the project root is not what you think it is -- check what the `-p` option was, and that will be the project root.

Apart from that, the update script will also leave a `tags.log` file next to your `tags` file, in which you can also check what happened there.

**Comment by IslandUsurper** [comment]
I'm having a similar problem. My .gutctags file is 
```
 --languages=php,javascript
 --langmap=php:.engine.inc.module.theme.install.php
 --php-kinds=cdfi
```
and tags.log has "ctags: Warning: Ignoring non-option in <redacted>/.gutctags". I believe, because of this, the langmap isn't being used, and my tags file only contains Javascript tags. The `-p` option is correct, and the ctags invocation looks right generally. The man page for ctags tells me I can use these options, so I can't figure out what the non-option is. I've even tried removing the last EOL byte, just in case.

I've ended up calling ctags myself with these options to seed the tags file. But then Gutentags doesn't update the PHP files.

**Comment by IslandUsurper** [comment]
This is apparently not Gutentags-specific. Running `ctags --options=.gutctags` also gives that error message.

**Comment by IslandUsurper** [comment]
`ctags --version`
"Exuberant Ctags 5.9~svn20110310"

**Comment by ludovicchabant** [comment]
I tried repro'ing it and I got the same error message from `ctags`.... until I realized that block of code you pasted in your first comment had one space at the beginning of each line! I removed the extra space and now it's working fine for me. Do you have that extra space as well locally?

**Comment by IslandUsurper** [comment]
:man_facepalming: I may very well have. I ended up removing the files and put the configuration in the `CTAGS` environment variable, but I'm testing it again and it seems to work now.

**Comment by ludovicchabant** [comment]
Cool, I'll close this then.
