### ISSUE TITLE
Creating tags fails on Windows when there's a space in the user directory.

### ISSUE THREAD

**Issue by cdespatie** [ludovicchabant/vim-gutentags#145]
Hey,

Gutentags seems to fail to create a tags file when the `user` directory contains a space on Windows (which is often the case on newer versions - I'm on 10). It's too bad, because I'd love to use this plugin on my Windows machines!

There's a PR open for this here that's been around for a while: https://github.com/ludovicchabant/vim-gutentags/pull/69, although I'm not sure if this actually fixes the issue for everyone or not. Last time I played around with this I couldn't get it to work even with the PR's changes.

Thanks!

**Comment by ludovicchabant** [comment]
Hi!

Is the space in the path to Gutentags itself, or in the path to your project's codebase, or in the path to the tags cache folder (if you're using that)? Or all the above?

That PR only fixes the first case AFAIK.

**Comment by cdespatie** [comment]
It's the space to Gutentags itself, I believe. I was attempting to use it without the cache folder, and my code directories don't have spaces in them, so I can't speak to the other two.

**Comment by ludovicchabant** [comment]
Hey there! I tried to put spaces everywhere: in the path to Gutentags, in the path to a temp repository I'm opening in Vim, and inside the repository itself. It worked as intended as far as I can tell. The only issue I had was that I sometimes got duplicate symbols because it was getting confused between uppercase and lowercase drive letter.

**Comment by cdespatie** [comment]
Yup, it appears to be working now! Not sure which of the recent changes fixed it, but I'm glad it did. Thanks!
