### ISSUE TITLE
Does it support async VIM 8

### ISSUE THREAD

**Issue by alex-shamshurin** [ludovicchabant/vim-gutentags#151]
1. Async or not?
2. What is the key difference from `xolox/easytags`
3. Does it support jsctags?

**Comment by trevordmiller** [comment]
Vim 8 async support would be sweet :)

**Comment by trevordmiller** [comment]
Related: https://github.com/ludovicchabant/vim-gutentags/issues/121

**Comment by ludovicchabant** [comment]
Heya!

It's async in a way, yes. Since I wrote this plugin before Vim 8 and neovim had any async API, what Gutentags has always been doing from the start is to spawn a background process via a batch file, and that process is the one that updates the tags. Vim stays responsive.

I have no idea what `xolox/easytags` does so I can't offer a constructive comparison. I'd be interested to read someone's pros/cons of both plugins though.

There is _some_ support for various `ctags` executables based on the project type. See `g:gutentags_project_info` and `g:gutentags_ctags_executable_{filetype}`.
