### ISSUE TITLE
Set maximum filesize for tags file?

### ISSUE THREAD

**Issue by anowlcalledjosh** [ludovicchabant/vim-gutentags#160]
Is there any way to limit the maximum size of the tags file generated by vim-gutentags (or if not, do you know if any ctags program has this feature)? I don't really need a 500MB tags file for my Vim plugins if I happen to open one of the plugin's files...

**Comment by ludovicchabant** [comment]
I don't know any `ctags` program that would do that, especially since they tend to hold a lot of data in memory so the file stays at 0Kb for a while and then suddenly goes to 700Mb upon exit.

You could check the file size in the `GutentagsUpdated` auto-command however, and do whatever you want there... I'm not sure what you could do though... trimming the file means you get a partial tags file, and a partial tags file is useless, so you might as well add some `.notags` file in the root folder to tell Gutentags to ignore it completely.

Note that most people clone the Vim plugins' repos, which means Gutentags recognizes each plugin as a separate project and ends up generating multiple small tags files instead of one giant one for your entire setup.

**Comment by anowlcalledjosh** [comment]
Unfortunately the tags file for [YouCompleteMe](https://github.com/Valloric/YouCompleteMe) alone ends up being 729MB for me, which is a bit of a problem when that's 50% of my free disk space!

The .notags file is a fine workaround though, especially since YCM is the only plugin that results in such a huge tags file as far as I can tell.
