### ISSUE TITLE
Error message with neovim

### ISSUE THREAD

**Issue by glacambre** [ludovicchabant/vim-gutentags#165]
This line https://github.com/ludovicchabant/vim-gutentags/blob/4304b67481a13612afc184f5f87e7ba70abbbc0c/plugin/gutentags.vim#L11
Should probably be
```vim
if v:version < 800 && !has("nvim")
```
Neovim's `v:version` is still `704`, even on nvim v.0.2.0, which has the needed job api.

Thank you for creating and maintaining vim-gutentags by the way, it's one of my favorite vim plugins!

**Comment by justinmk** [comment]
This change makes sense, but note that `v:version => 800` since Nvim 0.2.1.

**Comment by ludovicchabant** [comment]
I actually also realized that some Linux distribution, for some obscure reason, distribute Vim 7.4 with a whole bunch of patches applied (including `job`), which kind of make it a Vim 8, but it still reports a 7.x version... so since we check for the job API directly, I re-downgraded the Vim version check with 327bd979dd480a42b6edf3205136ac08cf349e8e.
