### ISSUE TITLE
Gutentags ignores `.ctags` files in project root

### ISSUE THREAD

**Issue by bsmith89** [ludovicchabant/vim-gutentags#17]
I don't know if this is a bug or a feature request, but I'm noticing that when ctags is run by gutentags it indexes everything in the project, even when I have a `.ctags` file with `--exclude=[something]`.

This may be outside the scope of the gutentags---I know there's a variable `g:gutentags_exclude` that has the desired behavior---but I'd like to get the same output from running `ctags -R` in the project root as I get with this plugin...without having exclusions defined globally in `$HOME/.ctags`, my `.vimrc`, or a vim modeline.

I'll take a look at the code myself and see if there's an easy fix, but I thought I'd put in an issue, too.

Edit: I also see `g:gutentags_options_file`, but again I'd rather avoid cluttering my `.vimrc`.  I guess I can set up an autocommand to reset that variable for each file I open...?

**Comment by bsmith89** [comment]
Okay, I'm learning more about the plugin and I see that it's _not_ just running `ctags` at the project root.  My trace output:

```
gutentags: Running: !/Users/bjsmith/Projects/dotfiles/home/.vim/bundle/vim-gutentags/plat/unix
/update_tags.sh -e "ctags" -t "/Users/bjsmith/.vim/bundle/vim-gutentags/tags" -p "/Users/bjsmi
th/.vim/bundle/vim-gutentags" > "/Users/bjsmith/.vim/bundle/vim-gutentags/tags.log" 2>&1 &
gutentags: In:      /Users/bjsmith/.vim/bundle/vim-gutentags
:!/Users/bjsmith/Projects/dotfiles/home/.vim/bundle/vim-gutentags/plat/unix/update_tags.sh -e
"ctags" -t "/Users/bjsmith/.vim/bundle/vim-gutentags/tags" -p "/Users/bjsmith/.vim/bundle/vim-
gutentags" > "/Users/bjsmith/.vim/bundle/vim-gutentags/tags.log" 2>&1 &
gutentags:
```

**Comment by ludovicchabant** [comment]
Hey, sorry I'm catching up with the issues here that I've neglected these past few weeks.

Gutentags is not running `ctags` in the project root because it's possible to have Gutentags "hide" the `tags` files away in a temp folder. This means the `tags` file is in a folder unrelated to the project root, but contains relative paths to the project's code files, so when you want to navigate to a tag, there's a good chance (depending on Vim's current working directory) that the file won't open. And using the `--tag-relative` gives ugly `../../../foo/bar` paths... maybe there's a magical combination of parameters that works, but I haven't found it so far.

So instead, Gutentags just runs ctags wherever and passes absolute paths to both the project directory and the tags file.

However, I just added with cff41764141b054474ba35414d110063ec874bde the ability for Gutentags to look for a `.ctags` file in the project root, and if it exists, pass it to `ctags` through the `--options` parameter. This seems to work as expected... re-open the issue if it causes problems. Thanks!

**Comment by madssj** [comment]
For some reason the .ctags file doesn't work as expected on OS X. Observe the following:

```
# no .ctags file exists
$ ctags -R --options=.ctags README.md
ctags: cannot open option file ".ctags" : No such file or directory
# now make the file, and observe the same error
$ touch .ctags
$ ctags -R --options=.ctags README.md
ctags: cannot open option file ".ctags" : No such file or directory
# moving the file into another name, will fix the problem
$ mv .ctags .gutentagsoptions
$ ctags -R --options=.gutentagoptions  README.md
$ ctags --version
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Mar 16 2015, 23:48:18
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex
```

Reading the man page for `ctags` it has a section about `FILES` which lists .ctags as a special file. So in order to get this to work properly, I think you need to rename your version to `.gutentagsoptions` or something which `ctags` doesn't use itself.

On a Linux box, I get a `Permission denied` error.

Does this work for anyone, with the `.ctags` options file?

**Comment by ludovicchabant** [comment]
Interesting, I didn't know that... but it _does_ work for me on OS X if `ctags` is not run from the same directory as the project. So:

```
cd myproject
ctags -R --options=.ctags .
```

...will indeed give me the errors you mentioned. But if I do:

```
cd ..
ctags -R -f myproject/tags --options=myproject/.ctags myproject
```

...then it works as expected.

Since Gutentags doesn't run `ctags` from the project root, I guess that's what makes it work... although hopefully that behaviour is the same across all platforms.

**Comment by madssj** [comment]
Indeed it does. I haven't checked, but I recall reading somewhere else, that gutentags runs ctags *from* the project dir sometimes?

Not running `ctags` from the directory makes using relative excludes not work, so do you have any thoughts for handling those?

**Comment by ludovicchabant** [comment]
Gutentags will run `ctags` from the project directory if you didn't specify any `g:gutentags_cache_dir` (_i.e._ the `tags` file will be at the root of your project instead of "hidden away" in a cache folder).

Mmmh but yeah, indeed that's a downside of the current approach. Unless I'm missing something, I can't figure out a combination of options and current directories that will make it work as expected for relative excludes when using "hidden" tags files... maybe in that case I need to generate the tags file with absolute paths in the project root, and move it at the end to the cache directory...?

**Comment by madssj** [comment]
Would the following work?

* Always run from the project directory, use absolute paths to output files
* Rename the options file to something else, which is not used by `ctags` internally

**Comment by ludovicchabant** [comment]
Well I tried a few more combinations but I'm now running into a weird bug (at least on OSX) where a local `.ctags` is not picked up (see [here](http://stackoverflow.com/questions/13042434/ctags-cannot-open-option-file-ctags) and [here](http://stackoverflow.com/questions/23056537/ctags-doesnt-use-my-custom-ctags-on-mac-os)). This tells me using a custom options filename may actually be safer... :(

The other problem is that it seems impossible to have both absolute paths in the tags file and relative exclude rules in the options file. It looks like the exclude rules are run against the same paths as what you'll get, so if you want absolute paths, the rules will run against absolute paths. Argh!

And using relative paths only works if the tags file is at the project root anyway -- this is because Vim will combine any relative paths with the directory of the tags file. And using `--tag-relative` is not super cool because it makes all your paths start with `../../../../..` or something.

**Comment by madssj** [comment]
I made a [test repository](https://github.com/madssj/vim-gutentags-options-test) so we have something more concrete to go from.

If you look at the crudely named `correcttags` file there, you'll see that it doesn't have any of said dot-paths, but that they are indeed just relative from the project root. That was archived by running `ctags` from the project directory, and that makes using relative excludes (for example) work fine.

We can rule out being able to use, or even have a file called `.ctags` as just having that file causes `ctags` to stop working, as we've both verified.

It seems, that the only viable way to fix this, would be to rename the options file. `ctags` itself is not going to be fixing that, so it'll have to be worked around, and always running `ctags` from the project root dir.

The reason for having absolute paths, would be to enable having the `tags` file outside the project root, and because it enables `vim` to then reference those files, so it wouldn't work having a `tags` file with relative (to the project dir) paths outside the project root, right?

**Comment by ludovicchabant** [comment]
That's right, the `tags` file must have absolute paths to make it possible to store it outside of the project root. However, `ctags` sadly ties this together with its "exclude" rules, so we can't have both.

So either you need to disable Gutentags' cache directory and keep your tags files at project roots (that's sad), or we need to get creative... for instance, now that Gutentags will be looking for a custom options file (say, `.gutentagsoptions`), we can do some processing on it. I don't know how error-prone it would be, but it's definitely possible to look for any line starting with `--exclude` in it, and if the value contains a slash, make it absolute, store that as a "processed options file" in the cache directory, and tell `ctags` to use that. Basically transform all relative exclude paths in the custom options file to be absolute. It wouldn't be too much work IMHO.

**Comment by madssj** [comment]
I feel like most magic should be avoided where possible, but I can't really come up with anything other that processing the file to add absolute paths.

**Comment by ludovicchabant** [comment]
Ok I finally had some free time to do this, see 3e2a65a2a4896ad54594b49aea5028a0ad54684b. I'm expecting some side effect bugs with this so make sure to open new bugs for that, thanks !

**Comment by madssj** [comment]
Excellent!

It'll be a little while before I can tinker with it though.
