### ISSUE TITLE
How do I enable gutentags for directories which are not version controlled?

### ISSUE THREAD

**Issue by jdhao** [ludovicchabant/vim-gutentags#234]
I have read the documentation of gutentags and it seems gutentags works for directories which are version controlled. 

I am writing a paper using LaTeX and I do not use version control. How should it enable gutentags for my LaTeX project if all the related file for this project is under folder `/home/jdhao/projects/paper_foo`?  I can not seem to find a way to do it.

**Comment by ludovicchabant** [comment]
Look for `g:gutentags_project_root`. This is a list of "markers" (a file or a directory) that Gutentags is trying to find in order to figure out what is your project's "root" directory. For version controlled projects, it's easy, as they have a `.git` or `.hg` or similar directory in their root. You could figure out what makes your project recognizable, so to speak, and add that in your `vimrc`.

If there's nothing really recognizable (no special file in your project), you can invent one and add it as a root marker. For instance, you could add an empty `.mypaperproj` file, and add that as a root in `g:gutentags_project_root`.

Alternatively, if you're working on something valuable, it's always good to add version control anyway :)

**Comment by jdhao** [comment]
Thanks for your reply. Right now, I just create an empty `.git`  folder. Then I can use gutentags.
