### ISSUE TITLE
Gutentags creates tags when browsing the help files

### ISSUE THREAD

**Issue by LemonBoy** [ludovicchabant/vim-gutentags#24]
Today I noticed nearly all the folders in my vim-plug handled bundle/ folder contained a 'tags' file, which I later discovered gets created when I browse the :help file provided by the plugin. 
It's not a major issue but it'd be nice if it didn't do so.

**Comment by ludovicchabant** [comment]
Gutentags is not doing anything if it doesn't find a "known" project root, so I assume each of the plugins in the bundle directory are in a git or mercurial repository or something? In that case, yeah it would generate tags if you opened a file from inside one of those repos (which would happen if you open a help file).

Frankly I don't know if there's anything to do here, since there's no difference between this case and when you actually want to work in one of those repos. I could make Gutentags check for a `.notags` file not only at the project root, but also in parent directories, so you could drop a `.notags` file in the bundle directory, but that would be annoying for you if you actually want to work on one of the plugins to contribute a patch and you want tags generated... unless you have some other idea?

**Comment by LemonBoy** [comment]
Hrm, what about bailing out early when the file I've opened is marked as read-only?

**Comment by dnhgff** [comment]
@LemonBoy  i think that is just going to crop up more edge cases. what if i'm looking at some code mounted on a read-only filesystem or another user on my system owns  and i still want to Ctl-] my way around. perhaps if you are concerned with cleanliness you can set g:gutentags_cache_dir? these files grow linearly with the number of projects visited and simply rm -r'ing the cache dir is always very simple and cheap form of garbage collection if you're filling up your /home partition or something

**Comment by ludovicchabant** [comment]
Yeah, and keep in mind there are source control systems like Perforce where files are all set to read-only until you explicitly "check-out" the ones you want to start editing.

However I think we can look at `&buftype` and, if it's `help`, bail out. Come to think of it, Gutentags should probably bail out if `&buftype` is anything that's not "normal" anyway (`quickfix` buffers, `nofile` buffers, etc. shouldn't have tags generated). So that should fix it, unless someone foresees a problem?

**Comment by LemonBoy** [comment]
This sounds definitely better.

**Comment by angolon** [comment]
I too would selfishly like to see this issue resolved - I'd offer to help but today is literally the first time I've ever looked at vimscript. Since installing gutentags vim has started to hang quite severely when opening help files.

I suspect (with no evidence whatsoever) that in my case it might be cygwin related - it seems like calls to `getftype` inside of `gutentags#get_project_root` are taking a stupidly long time.

    FUNCTION  gutentags#get_project_root()
    Called 1 time
    Total time:  22.540737
     Self time:  22.540737
    
    count  total (s)   self (s)
        1              0.000000     let l:path = gutentags#stripslash(a:path)
        1              0.000000     let l:previous_path = ""
        1              0.000000     let l:markers = g:gutentags_project_root[:]
        1              0.000000     if exists('g:ctrlp_root_markers')
                                        let l:markers += g:ctrlp_root_markers
                                    endif
        7              0.000000     while l:path != l:previous_path
       36              0.000000         for root in g:gutentags_project_root
       30             22.540737             if getftype(l:path . '/' . root) != ""
                                                let l:proj_dir = simplify(fnamemodify(l:path, ':p'))
                                                return gutentags#stripslash(l:proj_dir)
                                            endif
       30              0.000000         endfor
        6              0.000000         let l:previous_path = l:path
        6              0.000000         let l:path = fnamemodify(l:path, ':h')
        6              0.000000     endwhile
                                    call gutentags#throw("Can't figure out what tag file to use for: " . a:path)

**Comment by ludovicchabant** [comment]
Finally fixed with 02c80ad98a62a8a6995386c2d50e23dd28b51c3c, thanks for your patience!
