### ISSUE TITLE
Tags generation broken if `.ctags` is present under Windows.

### ISSUE THREAD

**Issue by vadz** [ludovicchabant/vim-gutentags#29]
It seems to be impossible to explicitly pass `.ctags` as the extra options file name to ctags under Windows, see [the bug report](https://sourceforge.net/p/ctags/bugs/366/), so just creating a `.ctags` file in the project root breaks the tag generation as the plugin detects its presence and passed `--options=.ctags` to ctags which then exits with an error.

The especially annoying thing is that it's enough to not specify `--options` at all for `.ctags` to be found and used, as can be seen with `ctags --verbose`, so just removing the lines adding `-o` option from `ctags.vim` fixes this for me because project and tag files directories are the same in my case. But I don't know what to do in case they are different (but why would they be anyhow?).

**Comment by ludovicchabant** [comment]
It's actually apparently a bit more complicated than that, since the behaviour for a `.ctags` file seems to differ between operating systems... anyhow, this was also causing other issues, so as of a couple commits ago, Gutentags will only pick up an options file called `.gutctags`, and pass that with the `-o` option to the update script. Note that this is the file you'll need to use if you're using the cache directory feature (i.e. where Gutentags "hides" the tag files away from the projects) and you also want to use relative exclude rules (see https://github.com/ludovicchabant/vim-gutentags/issues/17).
