### ISSUE TITLE
How to append external directory?

### ISSUE THREAD

**Issue by oren** [ludovicchabant/vim-gutentags#50]
I would like to access the standard go library from my own repo.
If I comment gutentags from my .vimrc and run `ctags -R /user/local/go/src .` it generate the correct tags file. Is there a way to tell gutentags about my external directory? I read in the docs about .gutctags but I am not sure what should be it's content. I tried this:
```
ctags
-R
/usr/local/go/src
.
```
and other variations but nothing worked.

**Comment by ludovicchabant** [comment]
The `.gutctags` file is supposed to have the same syntax as the `.ctags` file and other Ctags options files, so you can check the Ctags documentation about that. Typically, you wouldn't add "`ctags`" on the first line, since the file only contains options... I'm not quite sure if it supports adding more files and directories, though.

You can run `ctags` manually by passing `--options=/path/to/project/.gutctags` in order to test that, too, since that will be a lot easier to test than with Gutentags.

**Comment by oren** [comment]
it looks like I can achieve the same functionality using vim-go plugin. thanks!
