### ISSUE TITLE
:GutentagsGenerate not an editor command

### ISSUE THREAD

**Issue by IslandUsurper** [ludovicchabant/vim-gutentags#51]
I've been trying to figure out how to get my whole project tagged at once, and I found `:GutentagsGenerate` in the help file, so I tried it. However, Vim gave me "E492: Not an editor command: :GutentagsGenerate tags"

I think I should instead use ":GutentagsUpdate!", but it doesn't seem to get everything in my project.

**Comment by ludovicchabant** [comment]
Oh right, that's a documentation bug. The `GutentagsGenerate` command is gone since it was not super useful and too annoying to maintain.

Indeed, `GutentagsUpdate!` is what you would do to force a regeneration of your whole project from scratch. You typically don't need to do that -- frankly, the whole point of Gutentags is that everything is done for you in the background.

* Why do you want to manually generate your project's tags? (Gutentags will do that right away when you open the first file in the project)
* How do you figure that `GutentagsUpdate!` doesn't get everything in the project?

**Comment by IslandUsurper** [comment]
`:tag <some function in the same file>` didn't work. ;)

That problem was in ctags, though, not Gutentags. It didn't recognize Drupal's files as being PHP because they end in .module and .inc. Adding those to the langmap in .profile took care of it.

**Comment by ludovicchabant** [comment]
Cool, good to know :) I'll close the issue then, thanks.
