### ISSUE TITLE
Support for alternative tags executables

### ISSUE THREAD

**Issue by tkonolige** [ludovicchabant/vim-gutentags#56]
It would be nice to have support for language specific tags executables (For example [jsctags](https://www.npmjs.com/package/jsctags)). These executables do not always have flags with the same names as ctags. I suggest using something similar to what easytags uses: 
```vimscript
let g:easytags_languages = {
\   'language': {
\     'cmd': 'jsctags',
\       'args': [],
\       'fileoutput_opt': '-f',
\       'stdout_opt': '-f-',
\       'recurse_flag': '-R'
\   }
\}
```

**Comment by ludovicchabant** [comment]
I just added proper support for project-type-specific tags executables (see 52a1f72819e08c4c16fb263b6d1d0c99983f339a), but not yet for specific arguments. I suppose for now you could get away with wrapping the "real" executable inside a script that forwards ctags-standard arguments into other arguments... I'm curious to hear about what other people think, I don't know much about what other tags programs there are out there, and what CLI they have.

**Comment by tkonolige** [comment]
My only exposure has been to the easy_tags plugin. I think the interface it provides is easy to use. However, I do not think it is necessary.

The only issue I can see with using a wrapper is handling reading the `ctags.options` file.

**Comment by ejoubaud** [comment]
:+1:

I've been looking for a way to configure `gutentags` to work with `vim-gutentags`, but to no avail so far. The problem is that `vim-gutentags` doesn't support `--options` for option files, nor `--append`, and their support seems to be a hard-coded assumption of `gutentags`.

Also the failure is silent. As it's an example in [the gutentags doc](https://github.com/ludovicchabant/vim-gutentags/blob/master/doc/gutentags.txt#L232), I was expecting `let g:gutentags_ctags_executable_ruby = 'ripper-tags'` to just work, but it turned out it failed silently. Only a quick `ps aux | grep tags` let me know what command was rerunning, so I could rerun it and see what the error was:

```bash
➜ /bin/sh /Users/ejoubaud/.dotfiles/link/.vim/plugged/vim-gutentags/plat/unix/update_tags.sh -e ripper-tags -t /Users/ejoubaud/src/marketplace/tags -p /Users/ejoubaud/src/marketplace -s /Users/ejoubaud/src/marketplace/app/inputs/text_input.rb -o /Users/ejoubaud/.dotfiles/link/.vim/plugged/vim-gutentags/res/ctags.options
Locking tags file...
Removing references to: /Users/ejoubaud/src/marketplace/app/inputs/text_input.rb
grep -v /Users/ejoubaud/src/marketplace/app/inputs/text_input.rb "/Users/ejoubaud/src/marketplace/tags" > "/Users/ejoubaud/src/marketplace/tags.temp"
Running ctags
ripper-tags -f "/Users/ejoubaud/src/marketplace/tags.temp"  --options=/Users/ejoubaud/.dotfiles/link/.vim/plugged/vim-gutentags/res/ctags.options --append "/Users/ejoubaud/src/marketplace/app/inputs/text_input.rb" "/Users/ejoubaud/src/marketplace"
ripper-tags: invalid option: --options=/Users/ejoubaud/.dotfiles/link/.vim/plugged/vim-gutentags/res/ctags.options
```

**Comment by ludovicchabant** [comment]
Ok I've updated the help file with more information.

Since `ripper-tags` looks like a fairly popular plugin, if anybody made a wrapper to it to support `--append` and `--options` (I'm guess you could get away with making `--options` do nothing silently), you could post it somewhere and we could bundle it with Gutentags!
