### ISSUE TITLE
Long wait when editing files in home directory

### ISSUE THREAD

**Issue by rslindee** [ludovicchabant/vim-gutentags#67]
I recently installed Gutentags and, while it appears to work wonderfully when I open a file inside one of my projects with a .git folder, it takes EXTREMELY long (~30 seconds) for Vim to open a file in ~/ (such as my .vimrc)

I enabled the tracing and this is what I get when attempting to edit ~/.vimrc:

gutentags: Scanning buffer '/home/rslindee/.vimrc' for gutentags setup...
gutentags: Can't figure out what tag file to use... no gutentags support.

Note that the second line doesn't appear until after approximately 30 seconds of searching. I tried putting a .notags file in my ~/ directory, but it made no difference.

Any suggestions would be greatly appreciated, as I think this plugin shows a great deal of promise.

Edit - Additional info:

-The long delay doesn't seem to occur if I open Vim in the root directory. That said, the delay occurs if I attempt to open Vim inside something like /bin
-This is inside a Cygwin environment
-It seems like the algorithm for finding "project markers" in parent directories is taking way too long when there are no such project markers to be found

**Comment by ludovicchabant** [comment]
Interesting, I can't think of anything that would result in such a slow lookup for the project root... you could add some more traces into `autoload/gutentags.vim`, inside `gutentags#get_project_root`, where it does the `while` loop. This way you would maybe see exactly what directory causes problems.

Maybe there's something to do with a loop of symbolic links? Or with a parent directory that requires admin privileges and so Windows times out because of UAC? Or the terminal condition to stop navigating to parent folders is somehow not valid under Cygwin? (on Windows and *nix, Vim's `fnamemodify(path, ':h')` basically returns the same thing you passed in if you reached the root)

**Comment by ludovicchabant** [comment]
(haven't heard back)
