### ISSUE TITLE
GutentagsUpdate! should run on current directory, not file

### ISSUE THREAD

**Issue by blueyed** [ludovicchabant/vim-gutentags#86]
And/or there should be a way to specify another (optional) path.

**Comment by ludovicchabant** [comment]
In theory, `GutentagsUpdate` (no bang) updates the current file, and `GutentagsUpdate!` (bang) updates the whole project.

I agree that being able to pass some parameter to `GutentagsUpdate` would be nice, but it can get tricky when it's time to figure out what to remove from the existing `tags` file, and how to re-add what you really mean... Right now, the only 2 ways I know are "whole project" or "update a single file", hence the only 2 modes for `GutentagsUpdate`.

What exactly are you trying to do?

**Comment by blueyed** [comment]
I was trying to run it on the current project, but the current buffer happened to be a file from outside.

**Comment by ludovicchabant** [comment]
Ah ok, so maybe the problem is that you'd need some `statusline` indicator of what "project" the current file belong to, maybe? Otherwise I don't know how gutentags could run on a project that the current buffer doesn't belong to (unless we introduce the concept of a "project session", like VisualStudio/Eclipse/etc., but I don't think I want to go there).

**Comment by ludovicchabant** [comment]
Closing old issues.
