### ISSUE TITLE
gutentags and fugitive

### ISSUE THREAD

**Issue by HaleTom** [ludovicchabant/vim-gutentags#93]
The very popular `fugitive` plugin puts expects tags in `$root/.git`.

Is there a way to tell this plugin expect to find `tags` in the `.git` directory if there is one, and at project root otherwise?

**Comment by ludovicchabant** [comment]
I'm confused, what does Fugitive have to do with the `tags` file? Are you not mixing it up with Git tags, which is something different?

**Comment by HaleTom** [comment]
Fugitive sets the default location of tags to the .git directory. 

I'd expect strange effects if there were two tags files in play?

**Comment by dojoteef** [comment]
@ludovicchabant I am running into a similar issue. See [this post](http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html) by the author of [vim-fugitive](https://github.com/tpope/vim-fugitive) with an explanation of the approach @HaleTom  is referring to.

## My desire for the flexibility
I am actually trying to combine the approach in that blog post, but with minimal updates upon branch changes by using `git diff` rather than regenerating the entire `tags` file on branch change. `vim-gutentags` would then be used for intermediate updates while editing files.

Unless I am missing something, `vim-gutentags` does not appear to account for changes that occur to the structure of the file system outside of vim which is why I need to combine the approaches. It could probably be done with a simple listing and a hash of each file and then a scan to determine if any files in the project tree changed upon [focus gained event](http://vimdoc.sourceforge.net/htmldoc/autocmd.html#FocusGained), though it could be quite slow in a large project so this hybrid approach I am using would likely be more efficient (so I am not suggesting it makes sense to include in `vim-gutentags`).

## A potentially easy to implement solution
That said you could probably support what we want pretty simply by just adding a buffer local version of the global option `g:gutentags_tagfile`. Then a user could set `g:gutentags_project_root_finder` to their own root finder function and if they determine they are in a git repository they could then set the buffer local `b:gutentags_tagfile` to the appropriate value (in this case `$projectroot/.git/tags`). In the places you use `g:gutentags_tagfile` you would first check if `b:gutentags_tagfile` exists and use it, otherwise fallback to `g:gutentags_tagfile`.

Some nice additions would be:
* support buffer local versions of other global options where it makes sense
* break up `gutentags#get_project_root` into two functions:
 * keep the check for `g:gutentags_project_root_finder` at the top
 * make a `gutentags#default_get_project_root` that contains the rest of the function (that way users could call `gutentags#default_get_project_root` in their custom root finder if they do not want to write one or use one from a different plugin)

**Comment by ludovicchabant** [comment]
Thanks for the blog post link, that makes a lot more sense now! It's true that things like switching branches, pulling/updating, and other such operations that happen in the command line are completely unknown to Gutentags and therefore the tags are out of date until you manually run `:GutentagsUpdate!`, so a hook/callback to catch those makes sense.

However, that seems completely independent of whether the generated `tags` file is in the `.git` folder or not though -- the hook script could generate it anywhere, really. AFAICT putting it in the `.git` folder only gives you 2 things:

1. Fugitive will tell Vim to look for it there automatically if it exists.
2. you don't have to add it to your `.gitignore`.

The first of those 2 things is already done by Gutentags, who already tells Vim where the file is... so unless Fugitive does something else, the only reason to put it in the `.git` folder has nothing to do with Fugitive... also, if you don't want `tags` files in view, or in your `.gitignore`, Gutentags already supports generating the file in a "cache folder", although that folder is global for all projects (because I like being able to wipe it all at once to reclaim disk space, for instance)

So unless I'm missing something, putting that tags file in the `.git` folder is really down to a matter of preference, since it doesn't give you anything significant that isn't achieved some other way (again, unless I'm missing something). But hey, preference matters too -- that's why we use Vim and spend hours customizing it, right? 

The missing feature here is really to be able to set a custom `tags` file path on a per-project basis. I'm not sure I would support it by handling some buffer-local variable as a result... (it's not a per-file setting, it's per project, so I don't know why any setting should be per-file?). I think I would prefer something where you can tie some project marker to a path, like such:

```
let g:gutentags_project_tagfile_path = {
    \ '.git': ".git"
    }
```

This would tell Gutentags that when a project is a Git repo (it found `.git` as the root marker), it should use the `.git` folder as a base for generated files, instead of the default (which is either the project root, or the cache folder). But somehow changing the API for the root finder callback to also return other pieces of information, as you suggested, could work too, in case you want more custom tag file placements (but maybe a bit too overkill).

What do you think?

**Comment by HaleTom** [comment]
Unfortunately, you can't assume that a git directory is called `.git`. Sometimes the `.git` directory is external, pointed at by the contents of the *file* called `.git`.

The correct way to get the .git directory for the current directory is:
`git rev-parse --git-dir`

Perhaps the `tags` file location could be set by some logic like:
- `gutentags_tagfile_path()` if that function is defined and its return is non-blank
- `$(git rev-parse --git-dir)/tags` if `g:gutentags_use_git_dir == 1 and shell exit status == 0
- `gutentags#get_project_root() . "/tags"` otherwise

**Comment by dojoteef** [comment]
@ludovicchabant The tags file is not necessarily global per project. In fact the [tags](http://vimdoc.sourceforge.net/htmldoc/options.html#'tags') option can be set per buffer. There are valid use cases where this makes sense. Additionally the approach I mentioned of using a per buffer value for an override is actually employed by a number of popular plugins (search the [syntastic docs](https://github.com/scrooloose/syntastic/blob/master/doc/syntastic.txt) for `b:` to see examples).

@HaleTom makes a number of good points. You do have to use `$(git rev-parse --git-dir)`. I use that in my git hooks to get the tags file. Though I believe a simple check between `.git` and `.git/` can be used to determine if it is actually the git directory (at least other plugins that do project root finding use that distinction, see [vim-rooter](https://github.com/airblade/vim-rooter/blob/70c105cbcf3ce19b92ddec8fa498e49ada79744b/plugin/rooter.vim#L19) for example).

I think the use of a function like `gutentags_tagfile_path()` is not much different than using a buffer local variable in the sense that you cannot get that value once and assume it is valid globally like the plugin is currently doing. That only makes sense if you only ever open projects from one type of VCS, which seems like a limitation best not assumed by the plugin. I do not have a strong opinion one way or the other regarding the use of a buffer local or a `gutentags_tagfile_path`. I guess the function approach is more inline with what the plugin is currently doing.

**Comment by HaleTom** [comment]
@dojoteef Yes - I'd expect that something like `gutentags_tagfile_path()` would need to be called once for each buffer, because as you point out, `&tags` can be set per buffer.

**Comment by dojoteef** [comment]
@ludovicchabant I changed my approach and used a cache directory as you suggested, but unfortunately that means tags files can be orphaned in the directory. If you remove the project the tags will no longer be automatically deleted, so I made a [script](https://github.com/dojoteef/dotfiles/blob/master/bin/ctags_cleanup) that will clean up tags files if the associated directory no longer exists. Of course I have to manually run it (or possibly make a cron job), but it seems to work reasonably well.

If you do end up changing adding something like `gutentags_tagfile_path()` I will likely revisit my approach. Thanks for making a useful easy to use plugin!

**Comment by ludovicchabant** [comment]
I just pushed a new branch, `[buffer-tagfiles][1]`, that has some tentative implementation of this. Give it a try! Based on feedback we may iterate a bit on it before merging back in the main branch.

Here's how you do it:

* Set `g:gutentags_init_user_func` to the name of some custom function you wrote. This is a rename of the existing `g:gutentags_enabled_user_func`, so if you already had that, you can use it (it should still check for the old name).
* Make the function return `1` (see the documentation).
* Before returning, set `b:gutentags_tagfile` to some project-relative path. So, say, `.git/tags` if that's what you want. Right now you'd have to look up the directory tree yourself to figure out if this is indeed a Git repo... we can make that easier later.

Known problem: if you somehow set the tagfile to different paths depending on the current file (for [these kinds of things][2]), each buffer will only "see" the tagfile that it knows about -- so any tag operation would run on an incomplete database, which is sometimes what you want, and sometimes not.

[1]: https://github.com/ludovicchabant/vim-gutentags/tree/buffer-tagfiles
[2]: https://github.com/ludovicchabant/vim-gutentags/issues/95

**Comment by HaleTom** [comment]
Thanks a bunch for doing this! I've been spending my time on a patch for `tmuxinator`, but can now look at this. 

`fugitive` is prepending `~/repo/tmuxinator/.git/tags,` to my `&tags` already, but with the below VimL, it is not duplicated (why search the same file twice?) which seems just perfect.

I'm a VimL baby, but here's my try at this:

```viml
let g:gutentags_init_user_func = "SetGutentagsDirectory"
function! SetGutentagsDirectory(buffer_filename)
  let l:git_root=system('git rev-parse --git-dir 2>/dev/null')
  if v:shell_error
    let b:gutentags_tagfile = 'tags'
  else
    let b:gutentags_tagfile = '.git/tags'
  endif
  return 1
endfunction
```

Your feedback on this code would be appreciated. Especially how can I get rid of `l:git_root`?

Also @dojoteef, would you mind sharing a gist with your magic `git diff` in your hooks?

**Comment by dojoteef** [comment]
@ludovicchabant Sorry I have not had a chance to look at this earlier. I had a crazy month.

I noticed a few problems when using the branch. It seems if you *do not* specify `g:gutentags_cache_dir` then the code will [fallback to g:gutentags_tagfile](https://github.com/ludovicchabant/vim-gutentags/blob/29061ea6/autoload/gutentags/ctags.vim#L54-L69) which does not seem to be the expected behavior. Then if I change that code to use `a:tags_file` rather than `g:gutentags_tagfile` it treats `b:gutentags_tagfile` as a relative directory, so it tries to update `/project/root//project/root/.git/tags`. In correcting that by making `b:gutentags_file` equal to `.git/tags` it proceeds to correctly update the tags file with new tags, but will not remove old ones. The problem seems to be it's trying to remove tags for `<relative path to file from git root>`, but the tags file has it listed as `../<relative path to file from git root>`.

At that point I decided not to go down the rabbit hole, since I'm not intimately familiar with the structure of the code. Let me know if you need anything else with regards to testing.

@HaleTom No need for a gist, the [hooks](https://github.com/dojoteef/dotfiles/tree/f11f654d/link/.git_template/hooks) are part of my dotfiles repo, and this is the necessary [ctags update script](https://github.com/dojoteef/dotfiles/blob/f11f654d/bin/ctags_update).

**Comment by ludovicchabant** [comment]
Closing old issues. I never got time or motivation to work on these new features, but I'll happily look at a PR if anybody still needs it.
