### ISSUE TITLE
Simply allow custom ctags executable for different file type

### ISSUE THREAD

**Issue by hatelove85911** [ludovicchabant/vim-gutentags#95]
gutentags has a setting `g:gutentags_ctags_executable_{type}`, but it only works with a weird configuration  `g:gutentags_project_info` which I think useless.

What I want is simply define a variable: `g:gutentags_ctags_executable_{type}`, which will pick up the correct executable when it meets the corresponding file type.

My purpose is that I want to be able to use `jsctags` to generate tag files for js file, because the standard ctags support for js file is poor. 

If this feature can be supported, this will be a killing feature that all javascripter want. And I think in other language such as ruby, they also want use custom tag generators.

**Comment by ludovicchabant** [comment]
The problem I have is that there's not one tagfile per buffer... the tagfile is usually for the whole "project". If you're a web developer, your "project" most likely contains a mix of things: CSS code, JS code, maybe some Ruby/Python/whatever. So I assume you don't want to use `jsctags` for the whole thing, otherwise your CSS/Ruby/Python code would get indexed with the wrong executable.

Unless there's another way to go about this, I feel like what we need is a way to declare a certain number of tagfiles for a project -- instead of just one. So you would have a JS tagfile, CSS tagfile, etc. Each could be generated with their respective executable.

If we don't do that, what Gutentags would end up doing is: you edit `foo.css`, and it runs `ctags` with `tags` as the output file. Then you edit `bar.js` and it runs `jsctags` and overwrites `tags`! So your tagfile would flip flop between executables, probably resulting in Bad Things(tm).

**Comment by tkonolige** [comment]
@hatelove85911 I built a tool to "mush" different generators here: [https://github.com/tkonolige/ctags-shim](https://github.com/tkonolige/ctags-shim). It might be useful for you.

**Comment by hatelove85911** [comment]
@ludovicchabant , yes, what you said is right. I think there can be two possible solutions:

1. as you mentioned, one tag file for each file type, and we set `tags` option dynamically to include all the tag files.
[this project](https://github.com/still-dreaming-1/vim-project-tags) I think has implemented this feature

2. I don't know if it's possible: can we just have one tag file for a project and the content is combined of different tags generated by various tag generator??

The key issue I want to solve is just to use `jsctags` as the tag generation program for js files.

**Comment by ludovicchabant** [comment]
I actually like @tkonolige 's solution there, it's pretty elegant.

@hatelove85911, you second point might be difficult to implement. `ctags` programs can typically either regenerate a tags file, or append to it... but not replace parts of it.

I'm back to Gutentags work as part of my (increasingly long) rotation between my various open source projects, so I'll see if I can implement something like that this week.

**Comment by ludovicchabant** [comment]
Closing old issues. I never found time or motivation to work on this, and I believe that the solution is to have a separate "multi-ctags" tool anyway.
